<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sketchplugin</string>
		<string>jstalk</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>CocoaScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.cocoascript</string>
	<key>uuid</key>
	<string>05F0EB05-F72F-481D-8888-AA0F6942BAA2</string>
</dict>
</plist>
